site_name: OpenStack Environnement for trainees
site_url: http://www.redbeard-consulting.fr
repo_url: https://github.com/redbeard28/openstack-env-trainees
site_description: Build an OpenStack env for my trainees.
site_author: Jeremie CUADRADO aka redbeard28

theme: readthedocs
pages:
  - [ 'index.md', 'Home' ]
  - [ 'ssh_tunnel.md', 'Basics', 'SSH Tunnel']
  - [ 'prequisits.md', 'Home', 'Prequisits' ]
  - [ 'tested_os.md', 'Home', 'Tested for' ]
  - [ 'role_common', 'Ansible', 'Role Common']
  - [ 'role_gitlab_server', 'Ansible', 'Role Gitlab' ]
  - [ 'common_errors', 'Ansible', 'Commons Errors' ]
  - [ 'license.md', 'About', 'License' ]
  - [ 'about.md', 'About', 'about.md' ]